version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smart-support-backend
    image: smart-support-backend:latest
    environment:
      # Scibox API credentials (set via .env file or override)
      - SCIBOX_API_KEY=${SCIBOX_API_KEY}
      - API_TIMEOUT=${API_TIMEOUT:-20}
      - API_MAX_RETRIES=${API_MAX_RETRIES:-3}

      # Storage backend
      - STORAGE_BACKEND=${STORAGE_BACKEND:-sqlite}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/embeddings.db}

      # Python environment
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/backend
    ports:
      - "8000:8000"
    volumes:
      # Persist embeddings database
      - embeddings-data:/app/data
      # Development: mount source code for hot reload (comment out for production)
      # - ./src:/app/src
      # - ./backend/src:/app/backend/src
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - smart-support-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Frontend UI Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-support-frontend
    image: smart-support-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - smart-support-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  embeddings-data:
    driver: local

networks:
  smart-support-network:
    driver: bridge
